# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7.2'

      - name: Update
        shell: 'script --return --quiet --command "bash {0}"'
        run: sudo apt-get update
      - name: Install cURL Headers
        shell: 'script --return --quiet --command "bash {0}"'
        run: sudo apt-get install libcurl4 libcurl4-openssl-dev
      - name: Install dependencies
        shell: 'script --return --quiet --command "bash {0}"'
        run: bundle install
      - name: Run tests
        shell: 'script --return --quiet --command "bash {0}"'
        run: rspec spec